#!/usr/bin/env python3
"""
claude-review — AI-powered PR reviewer CLI
Usage: claude-review --pr https://github.com/owner/repo/pull/123
"""

import argparse
import json
import os
import re
import subprocess
import sys
import urllib.request
import urllib.parse

GITHUB_API = "https://api.github.com"
ANTHROPIC_API = "https://api.anthropic.com/v1/messages"

def gh_api(url, token):
    """Make an authenticated GitHub API request."""
    req = urllib.request.Request(url)
    req.add_header("Authorization", f"token {token}")
    req.add_header("Accept", "application/vnd.github.v3+json")
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read())

def get_pr_details(pr_url, token):
    """Extract owner/repo/pr_number from URL and fetch PR data."""
    # Parse URL patterns like:
    # https://github.com/owner/repo/pull/123
    # https://github.com/owner/repo/pull/123#issuecomment-456
    match = re.match(r'github\.com/([^/]+)/([^/]+)/pull/(\d+)', pr_url)
    if not match:
        raise ValueError(f"Invalid PR URL: {pr_url}")
    owner, repo, pr_num = match.groups()
    
    # Get PR details
    pr_data = gh_api(f"{GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_num}", token)
    
    # Get diff
    diff_url = f"{GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_num}"
    diff_req = urllib.request.Request(diff_url)
    diff_req.add_header("Authorization", f"token {token}")
    diff_req.add_header("Accept", "application/vnd.github.v3.diff")
    with urllib.request.urlopen(diff_req, timeout=15) as resp:
        diff = resp.read().decode('utf-8', errors='replace')
    
    # Get list of changed files
    files_url = f"{GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_num}/files"
    files_data = gh_api(files_url, token)
    changed_files = [f['filename'] for f in files_data]
    
    return {
        "owner": owner,
        "repo": repo,
        "pr_number": int(pr_num),
        "title": pr_data['title'],
        "body": pr_data['body'] or "",
        "author": pr_data['user']['login'],
        "state": pr_data['state'],
        "additions": pr_data.get('additions', 0),
        "deletions": pr_data.get('deletions', 0),
        "changed_files": changed_files,
        "diff": diff[:15000]  # Truncate for API limits
    }

def call_claude_api(diff_text, pr_info, api_key):
    """Call Claude API to analyze the PR diff."""
    changed_files = ", ".join(pr_info['changed_files'][:10])
    if len(pr_info['changed_files']) > 10:
        changed_files += f" and {len(pr_info['changed_files']) - 10} more"
    
    prompt = f"""You are an expert code reviewer. Analyze this pull request and provide a structured review.

## PR Info
- **Title**: {pr_info['title']}
- **Author**: @{pr_info['author']}
- **Changed files**: {changed_files}
- **Lines changed**: +{pr_info['additions']} / -{pr_info['deletions']}

## PR Description
{pr_info['body'] or '(no description)'}

## Diff (truncated)
{diff_text}

## Your Task
Analyze this PR diff and output a structured Markdown review with these exact sections:

### 📋 Summary
[2-3 sentence summary of what this PR does]

### ⚠️ Risks
- [risk 1]
- [risk 2]
- [risk 3, if applicable, otherwise "No significant risks identified"]

### 💡 Improvement Suggestions
- [suggestion 1]
- [suggestion 2]
- [suggestion 3, if applicable]

### 🎯 Confidence Score
**Low / Medium / High** — based on how confident you are in this review given the information available

### 📝 Additional Notes
[Any other observations: testing concerns, follow-up suggestions, etc.]

Be specific, constructive, and actionable. Do not be vague."""

    payload = {
        "model": "claude-sonnet-4-20250514",
        "max_tokens": 1200,
        "messages": [{"role": "user", "content": prompt}]
    }
    
    req = urllib.request.Request(
        ANTHROPIC_API,
        data=json.dumps(payload).encode('utf-8'),
        headers={
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
            "Content-Type": "application/json"
        },
        method="POST"
    )
    
    with urllib.request.urlopen(req, timeout=30) as resp:
        result = json.loads(resp.read())
    
    return result["content"][0]["text"]

def format_output(review_text, pr_info):
    """Format the review as structured Markdown."""
    header = f"""# 🔍 PR Review: #{pr_info['pr_number']} — {pr_info['title']}

**Repository**: [{pr_info['owner']}/{pr_info['repo']}](https://github.com/{pr_info['owner']}/{pr_info['repo']})  
**Author**: @{pr_info['author']}  
**Files changed**: {len(pr_info['changed_files'])} (+{pr_info['additions']} / -{pr_info['deletions']})  
**Review generated by**: Claude (claude-sonnet-4-20250514) via `claude-review` CLI

---

{review_text}

---
*Review generated automatically by claude-review CLI*  
*https://github.com/claude-builders-bounty/claude-builders-bounty*
"""
    return header

def main():
    parser = argparse.ArgumentParser(description="AI-powered PR reviewer")
    parser.add_argument("--pr", required=True, help="GitHub PR URL")
    parser.add_argument("--github-token", default=os.environ.get("GITHUB_TOKEN"), help="GitHub API token")
    parser.add_argument("--anthropic-key", default=os.environ.get("ANTHROPIC_API_KEY"), help="Anthropic API key")
    parser.add_argument("--output", "-o", help="Output file (default: stdout)")
    parser.add_argument("--post-comment", action="store_true", help="Post review as PR comment")
    
    args = parser.parse_args()
    
    if not args.github_token:
        print("Error: --github-token or GITHUB_TOKEN env var required", file=sys.stderr)
        sys.exit(1)
    if not args.anthropic_key:
        print("Error: --anthropic-key or ANTHROPIC_API_KEY env var required", file=sys.stderr)
        sys.exit(1)
    
    print(f"Fetching PR: {args.pr}", file=sys.stderr)
    pr_info = get_pr_details(args.pr, args.github_token)
    print(f"PR #{pr_info['pr_number']} — {pr_info['title']}", file=sys.stderr)
    print(f"Changed files: {len(pr_info['changed_files'])} (+{pr_info['additions']}/-{pr_info['deletions']})", file=sys.stderr)
    
    print("Analyzing with Claude...", file=sys.stderr)
    review = call_claude_api(pr_info['diff'], pr_info, args.anthropic_key)
    
    output = format_output(review, pr_info)
    
    if args.output:
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(output)
        print(f"Review written to {args.output}", file=sys.stderr)
    else:
        print(output)
    
    if args.post_comment:
        comment_url = f"{GITHUB_API}/repos/{pr_info['owner']}/{pr_info['repo']}/issues/{pr_info['pr_number']}/comments"
        payload = {"body": output}
        req = urllib.request.Request(
            comment_url,
            data=json.dumps(payload).encode('utf-8'),
            headers={"Authorization": f"token {args.github_token}", "Content-Type": "application/json"},
            method="POST"
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            print(f"Comment posted: {resp.geturl()}", file=sys.stderr)

if __name__ == "__main__":
    main()
