#!/usr/bin/env bash
#────────────────────────────────────────────────────────────────────────────
# changelog.sh — Generate CHANGELOG.md from Git History
#────────────────────────────────────────────────────────────────────────────
# Usage: bash changelog.sh [--repo /path/to/repo] [--output CHANGELOG.md]
#        ./changelog.sh                     # auto-detect repo
#────────────────────────────────────────────────────────────────────────────

set -euo pipefail

REPO_DIR="${1:-.}"
OUTPUT_FILE="${2:-CHANGELOG.md}"

cd "$REPO_DIR"

# Detect last tag
LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
SINCE_FLAG="--since=$(git log --reverse --format=%ai | head -1 2>/dev/null || echo "")"

if [[ -n "$LAST_TAG" ]]; then
  COMMITS=$(git log "$LAST_TAG..HEAD" --format="%H|%s|%an|%ad" --date=short 2>/dev/null || echo "")
  TAG_LINE="## [$LAST_TAG]"
  SINCE_REF="since $LAST_TAG"
else
  COMMITS=$(git log --format="%H|%s|%an|%ad" -50 2>/dev/null || echo "")
  TAG_LINE="# Changelog"
  SINCE_REF="last 50 commits"
fi

# Category mapping (conventional commits)
declare -A CATEGORIES=(
  ["feat"]="Added"
  ["fix"]="Fixed"
  ["perf"]="Improved"
  ["refactor"]="Changed"
  ["docs"]="Changed"
  ["test"]="Changed"
  ["chore"]="Changed"
  ["ci"]="Changed"
  ["build"]="Changed"
  ["BREAKING CHANGE"]="Removed"
)

# Build sections
declare -A sections=(
  ["Added"]=""
  ["Fixed"]=""
  ["Improved"]=""
  ["Changed"]=""
  ["Removed"]=""
)

add_to_section() {
  local cat="$1"
  local msg="$2"
  local hash="$3"
  local author="$4"
  
  local formatted="- $msg *([\`$hash\`])*"
  sections["$cat"]="${sections[$cat]}\n$formatted"
}

while IFS='|' read -r hash msg author date; do
  [[ -z "$hash" ]] && continue
  
  # conventional commit prefix
  if [[ "$msg" =~ ^([a-zA-Z]+)(\(.+\))?:\ +(.*) ]]; then
    prefix="${BASH_REMATCH[1]}"
    body="${BASH_REMATCH[3]}"
  else
    prefix="misc"
    body="$msg"
  fi
  
  # Map to category
  cat="${CATEGORIES[$prefix]:-Changed}"
  add_to_section "$cat" "$body" "${hash:0:7}" "$author"
done <<< "$COMMITS"

# Render
{
  echo "# Changelog"
  echo ""
  echo "*Auto-generated from git history — $SINCE_REF*"
  echo ""
  echo "Generated: $(date '+%Y-%m-%d')"
  echo ""
  
  for cat in "Added" "Fixed" "Improved" "Changed" "Removed"; do
    content="${sections[$cat]}"
    if [[ -n "$content" ]]; then
      echo "## $cat"
      echo -e "$content"
      echo ""
    fi
  done
  
  echo "---"
  echo "*Generated by changelog.sh — Claude Code skill*"
} > "$OUTPUT_FILE"

echo "✓ CHANGELOG.md written — $(wc -l < "$OUTPUT_FILE") lines"
echo "  ($(git rev-parse --short HEAD 2>/dev/null || echo 'local') @ $(date '+%Y-%m-%d %H:%M'))"
cat "$OUTPUT_FILE"